# Generated by Django 6.0.5 on 2026-05-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('sigle', models.CharField(blank=True, max_length=20)),
                ('siege_social', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(blank=True, max_length=50)),
                ('capacite', models.IntegerField()),
                ('kilometrage', models.IntegerField(default=0)),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_service', 'En service'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='en_service', max_length=20)),
                ('date_visite_technique', models.DateField(blank=True, null=True)),
                ('date_assurance', models.DateField(blank=True, null=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='transport.compagnie')),
            ],
            options={
                'verbose_name_plural': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agences', to='transport.compagnie')),
            ],
        ),
    ]
