# Generated by Django 6.0.5 on 2026-05-19 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_permis', models.CharField(max_length=50, unique=True)),
                ('date_expiration_permis', models.DateField(blank=True, null=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('annees_experience', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('repos', 'En repos'), ('inactif', 'Inactif')], default='disponible', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chauffeurs/')),
                ('actif', models.BooleanField(default=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs', to='transport.compagnie')),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_depart', models.CharField(max_length=50)),
                ('ville_arrivee', models.CharField(max_length=50)),
                ('distance_km', models.IntegerField(help_text='Distance en kilomètres')),
                ('duree_estimee_heures', models.FloatField(help_text='Durée estimée en heures')),
                ('prix_base', models.IntegerField(help_text='Prix du billet en FCFA')),
                ('actif', models.BooleanField(default=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='transport.compagnie')),
            ],
            options={
                'ordering': ['ville_depart', 'ville_arrivee'],
                'unique_together': {('compagnie', 'ville_depart', 'ville_arrivee')},
            },
        ),
    ]
