# Generated by Django 6.0.5 on 2026-05-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_chauffeur_trajet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('heure_arrivee_prevue', models.TimeField(blank=True, null=True)),
                ('prix', models.IntegerField(help_text='Prix du billet en FCFA')),
                ('places_disponibles', models.IntegerField()),
                ('statut', models.CharField(choices=[('programme', 'Programmé'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='programme', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.bus')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.chauffeur')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.trajet')),
            ],
            options={
                'ordering': ['-date_depart', '-heure_depart'],
            },
        ),
    ]
