# Generated by Django 6.0.5 on 2026-05-19 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_voyage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('type_client', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20)),
                ('cni', models.CharField(blank=True, help_text="Numéro de carte d'identité", max_length=50)),
                ('ville_residence', models.CharField(blank=True, max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('nombre_voyages', models.IntegerField(default=0, help_text='Nombre total de voyages effectués')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reservation', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre_places', models.IntegerField(default=1)),
                ('montant_total', models.IntegerField(help_text='Montant total en FCFA')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payée'), ('annulee', 'Annulée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire')], max_length=20)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agence', models.ForeignKey(blank=True, help_text='Agence où la réservation a été faite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.client')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.voyage')),
            ],
            options={
                'ordering': ['-date_reservation'],
            },
        ),
    ]
