# Generated by Django 6.0.5 on 2026-05-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_client_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='montant_total',
            field=models.IntegerField(blank=True, help_text='Calculé automatiquement'),
        ),
    ]
