# Generated by Django 6.0.5 on 2026-05-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_reservation_montant_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_suivi', models.CharField(blank=True, max_length=20, unique=True)),
                ('expediteur_nom', models.CharField(max_length=100)),
                ('expediteur_telephone', models.CharField(max_length=20)),
                ('destinataire_nom', models.CharField(max_length=100)),
                ('destinataire_telephone', models.CharField(max_length=20)),
                ('description', models.CharField(help_text='Contenu du colis', max_length=200)),
                ('poids_kg', models.FloatField(help_text='Poids en kilogrammes')),
                ('prix', models.IntegerField(help_text='Prix en FCFA')),
                ('statut', models.CharField(choices=[('enregistre', 'Enregistré'), ('en_transit', 'En transit'), ('arrive', 'Arrivé à destination'), ('livre', 'Livré'), ('retourne', 'Retourné')], default='enregistre', max_length=20)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agence_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_recus', to='transport.agence')),
                ('agence_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_envoyes', to='transport.agence')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis', to='transport.compagnie')),
                ('voyage', models.ForeignKey(blank=True, help_text='Voyage sur lequel le colis est transporté', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis', to='transport.voyage')),
            ],
            options={
                'verbose_name_plural': 'Colis',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
