# Generated by Django 6.0.5 on 2026-06-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_reservation_options_colis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_reservation']},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant_total',
            field=models.IntegerField(blank=True, default=0, help_text='Calculé automatiquement'),
        ),
    ]
