# Generated by Django 6.0.5 on 2026-06-22 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('poste', models.CharField(choices=[('responsable', "Responsable d'agence"), ('guichetier', 'Guichetier / billettiste'), ('caissier', 'Caissier'), ('agent_colis', 'Agent colis'), ('agent_transfert', "Agent transfert d'argent"), ('manutentionnaire', 'Manutentionnaire / bagagiste'), ('comptable', 'Comptable'), ('securite', 'Agent de sécurité'), ('autre', 'Autre')], default='guichetier', max_length=20)),
                ('cni', models.CharField(blank=True, help_text="Numéro de carte d'identité", max_length=50)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('salaire', models.IntegerField(blank=True, help_text='Salaire mensuel en FCFA', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='transport.agence')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='transport.compagnie')),
            ],
            options={
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='TransfertArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_transfert', models.CharField(blank=True, max_length=20, unique=True)),
                ('expediteur_nom', models.CharField(max_length=100)),
                ('expediteur_telephone', models.CharField(max_length=20)),
                ('beneficiaire_nom', models.CharField(max_length=100)),
                ('beneficiaire_telephone', models.CharField(max_length=20)),
                ('montant', models.IntegerField(help_text='Montant envoyé en FCFA')),
                ('frais', models.IntegerField(default=0, help_text='Frais de transfert en FCFA')),
                ('code_retrait', models.CharField(blank=True, help_text='Code secret remis au bénéficiaire', max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de retrait'), ('retire', 'Retiré'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_retrait', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('agence_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_envoyes', to='transport.agence')),
                ('agence_retrait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_recus', to='transport.agence')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='transport.compagnie')),
            ],
            options={
                'verbose_name_plural': "Transferts d'argent",
                'ordering': ['-date_envoi'],
            },
        ),
    ]
