# Generated by Django 6.0.5 on 2026-06-22 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_employe_transfertargent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion lié à cet employé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employe',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un PDG (toute la compagnie)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='transport.agence'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('pdg', 'PDG / Directeur général'), ('responsable', "Responsable d'agence"), ('guichetier', 'Guichetier / billettiste'), ('caissier', 'Caissier'), ('agent_colis', 'Agent colis'), ('agent_transfert', "Agent transfert d'argent"), ('manutentionnaire', 'Manutentionnaire / bagagiste'), ('comptable', 'Comptable'), ('rh', 'Responsable RH / recrutement'), ('securite', 'Agent de sécurité'), ('autre', 'Autre')], default='guichetier', max_length=20),
        ),
    ]
