# Generated by Django 6.0.5 on 2026-06-23 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_employe_user_alter_employe_agence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_crees', to='transport.employe', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_creees', to='transport.employe', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='transfertargent',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to='transport.employe', verbose_name='Créé par'),
        ),
    ]
