# Generated by Django 6.0.5 on 2026-06-23 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_colis_cree_par_reservation_cree_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('pdg', 'PDG / Directeur général'), ('responsable', "Responsable d'agence"), ('guichetier', 'Guichetier / billettiste'), ('caissier', 'Caissier'), ('agent_colis', 'Agent colis'), ('agent_transfert', "Agent transfert d'argent"), ('manutentionnaire', 'Manutentionnaire / bagagiste'), ('comptable', 'Comptable'), ('rh', 'Responsable RH / recrutement'), ('resp_maintenance', 'Responsable maintenance'), ('securite', 'Agent de sécurité'), ('autre', 'Autre')], default='guichetier', max_length=20),
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('vidange', 'Vidange moteur'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('revision', 'Révision générale'), ('boite_vitesse', 'Vidange boîte de vitesse'), ('courroie', 'Courroie'), ('batterie', 'Batterie'), ('climatisation', 'Climatisation'), ('carrosserie', 'Carrosserie'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'entretien")),
                ('date_entretien', models.DateField(verbose_name="Date de l'entretien")),
                ('kilometrage', models.PositiveIntegerField(default=0, verbose_name='Kilométrage du bus')),
                ('cout', models.PositiveIntegerField(default=0, verbose_name='Coût (FCFA)')),
                ('description', models.TextField(blank=True, verbose_name='Détails / pièces changées')),
                ('prochain_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prochaine échéance (km)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='transport.bus', verbose_name='Bus')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to='transport.employe', verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Entretien',
                'verbose_name_plural': 'Entretiens',
                'ordering': ['-date_entretien'],
            },
        ),
        migrations.CreateModel(
            name='PleinCarburant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_plein', models.DateField(verbose_name='Date du plein')),
                ('litres', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Litres')),
                ('montant', models.PositiveIntegerField(default=0, verbose_name='Montant (FCFA)')),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilométrage')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pleins', to='transport.bus', verbose_name='Bus')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleins_crees', to='transport.employe', verbose_name='Enregistré par')),
                ('voyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleins', to='transport.voyage', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Plein de carburant',
                'verbose_name_plural': 'Pleins de carburant',
                'ordering': ['-date_plein'],
            },
        ),
    ]
