# Generated by Django 6.0.5 on 2026-07-01 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0012_client_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['nom', 'prenom'], 'verbose_name_plural': 'Employes'},
        ),
        migrations.AlterField(
            model_name='client',
            name='cni',
            field=models.CharField(blank=True, help_text="Numero de carte d'identite", max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_voyages',
            field=models.IntegerField(default=0, help_text='Nombre total de voyages effectues'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion lie a cette fiche client (app mobile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='colis',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_crees', to='transport.employe', verbose_name='Cree par'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='statut',
            field=models.CharField(choices=[('enregistre', 'Enregistre'), ('en_transit', 'En transit'), ('arrive', 'Arrive a destination'), ('livre', 'Livre'), ('retourne', 'Retourne')], default='enregistre', max_length=20),
        ),
        migrations.AlterField(
            model_name='colis',
            name='voyage',
            field=models.ForeignKey(blank=True, help_text='Voyage sur lequel le colis est transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis', to='transport.voyage'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='cni',
            field=models.CharField(blank=True, help_text="Numero de carte d'identite", max_length=50),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('pdg', 'PDG / Directeur general'), ('responsable', "Responsable d'agence"), ('guichetier', 'Guichetier / billettiste'), ('caissier', 'Caissier'), ('agent_colis', 'Agent colis'), ('agent_transfert', "Agent transfert d'argent"), ('manutentionnaire', 'Manutentionnaire / bagagiste'), ('comptable', 'Comptable'), ('rh', 'Responsable RH / recrutement'), ('resp_maintenance', 'Responsable maintenance'), ('securite', 'Agent de securite'), ('autre', 'Autre')], default='guichetier', max_length=20),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion lie a cet employe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='cout',
            field=models.PositiveIntegerField(default=0, verbose_name='Cout (FCFA)'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_crees', to='transport.employe', verbose_name='Enregistre par'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='description',
            field=models.TextField(blank=True, verbose_name='Details / pieces changees'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometrage du bus'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='prochain_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prochaine echeance (km)'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='type_entretien',
            field=models.CharField(choices=[('vidange', 'Vidange moteur'), ('freins', 'Freins'), ('pneus', 'Pneus'), ('revision', 'Revision generale'), ('boite_vitesse', 'Vidange boite de vitesse'), ('courroie', 'Courroie'), ('batterie', 'Batterie'), ('climatisation', 'Climatisation'), ('carrosserie', 'Carrosserie'), ('autre', 'Autre')], max_length=20, verbose_name="Type d'entretien"),
        ),
        migrations.AlterField(
            model_name='pleincarburant',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pleins_crees', to='transport.employe', verbose_name='Enregistre par'),
        ),
        migrations.AlterField(
            model_name='pleincarburant',
            name='kilometrage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometrage'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Agence ou la reservation a ete faite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.agence'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_creees', to='transport.employe', verbose_name='Cree par'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Especes'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant_total',
            field=models.IntegerField(blank=True, default=0, help_text='Calcule automatiquement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payee'), ('annulee', 'Annulee'), ('remboursee', 'Remboursee')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='distance_km',
            field=models.IntegerField(help_text='Distance en kilometres'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='duree_estimee_heures',
            field=models.FloatField(help_text='Duree estimee en heures'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='code_retrait',
            field=models.CharField(blank=True, help_text='Code secret remis au beneficiaire', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to='transport.employe', verbose_name='Cree par'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='montant',
            field=models.IntegerField(help_text='Montant envoye en FCFA'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de retrait'), ('retire', 'Retire'), ('annule', 'Annule'), ('rembourse', 'Rembourse')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='statut',
            field=models.CharField(choices=[('programme', 'Programme'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('annule', 'Annule')], default='programme', max_length=20),
        ),
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Numero du siege')),
                ('occupe', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sieges', to='transport.reservation')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieges', to='transport.voyage')),
            ],
            options={
                'ordering': ['voyage', 'numero'],
                'unique_together': {('voyage', 'numero')},
            },
        ),
    ]
