# Generated by Django 6.0.5 on 2026-07-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_alter_employe_options_alter_client_cni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type_piece',
            field=models.CharField(blank=True, choices=[('cni', "Carte nationale d'identite"), ('passeport', 'Passeport'), ('acte_naissance', 'Acte de naissance'), ('carte_pro', 'Carte professionnelle'), ('permis', 'Permis de conduire'), ('autre', 'Autre piece')], help_text="Type de piece d'identite", max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='cni',
            field=models.CharField(blank=True, help_text="Numero de la piece d'identite", max_length=50),
        ),
    ]
