# Generated by Django 6.0.5 on 2026-07-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_client_type_piece_alter_client_cni'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='voyageur_nom',
            field=models.CharField(blank=True, help_text='Nom du voyageur de ce billet', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyageur_numero_piece',
            field=models.CharField(blank=True, help_text='Numero de piece du voyageur', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyageur_prenom',
            field=models.CharField(blank=True, help_text='Prenom du voyageur', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyageur_telephone',
            field=models.CharField(blank=True, help_text='Telephone du voyageur', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyageur_type_piece',
            field=models.CharField(blank=True, help_text='Type de piece du voyageur', max_length=20),
        ),
    ]
