# Generated by Django 6.0.5 on 2026-07-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_reservation_voyageur_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre de la promotion', max_length=120)),
                ('texte', models.TextField(help_text='Description de la promotion')),
                ('image', models.ImageField(blank=True, help_text='Image de la promotion', null=True, upload_to='promotions/')),
                ('date_debut', models.DateField(help_text='Date de debut de validite')),
                ('date_fin', models.DateField(help_text='Date de fin de validite')),
                ('actif', models.BooleanField(default=True, help_text='Decochez pour masquer')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-date_creation'],
            },
        ),
    ]
