# Generated by Django 6.0.5 on 2026-07-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='service',
            field=models.CharField(choices=[('voyage', 'Reservation de voyage'), ('colis', 'Envoi de colis'), ('transfert', "Transfert d'argent"), ('aucun', 'Aucun')], default='aucun', help_text='Vers quel service renvoie la promotion', max_length=20),
        ),
    ]
