# Generated by Django 6.0.5 on 2026-07-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_promotion_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(blank=True, max_length=20, unique=True)),
                ('expediteur_nom', models.CharField(max_length=100)),
                ('expediteur_telephone', models.CharField(max_length=20)),
                ('destinataire_nom', models.CharField(max_length=100)),
                ('destinataire_telephone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('poids_estime', models.FloatField(help_text='Poids estime en kg')),
                ('valeur_declaree', models.IntegerField(default=0, help_text='Valeur declaree en FCFA')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validee (colis cree)'), ('annulee', 'Annulee')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('agence_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_colis_arrivee', to='transport.agence')),
                ('agence_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_colis_depart', to='transport.agence')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_colis', to='transport.client')),
                ('colis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='transport.colis')),
            ],
            options={
                'verbose_name': 'Demande de colis',
                'verbose_name_plural': 'Demandes de colis',
                'ordering': ['-date_demande'],
            },
        ),
    ]
