# Generated by Django 6.0.5 on 2026-07-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0018_demandecolis'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecolis',
            name='poids_reel',
            field=models.FloatField(blank=True, help_text="Poids reel pese a l'agence (kg)", null=True),
        ),
        migrations.AddField(
            model_name='demandecolis',
            name='prix',
            field=models.IntegerField(blank=True, help_text="Prix fixe par l'agence (FCFA)", null=True),
        ),
    ]
