# Generated by Django 6.0.5 on 2026-07-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_demandecolis_poids_reel_demandecolis_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(blank=True, max_length=20, unique=True)),
                ('expediteur_nom', models.CharField(max_length=100)),
                ('expediteur_telephone', models.CharField(max_length=20)),
                ('beneficiaire_nom', models.CharField(max_length=100)),
                ('beneficiaire_telephone', models.CharField(max_length=20)),
                ('montant', models.IntegerField(help_text='Montant a envoyer en FCFA')),
                ('frais', models.IntegerField(blank=True, help_text="Frais fixes par l'agence", null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validee (transfert cree)'), ('annulee', 'Annulee')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('agence_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_depart', to='transport.agence')),
                ('agence_retrait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_retrait', to='transport.agence')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert', to='transport.client')),
                ('transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='transport.transfertargent')),
            ],
            options={
                'verbose_name': 'Demande de transfert',
                'verbose_name_plural': 'Demandes de transfert',
                'ordering': ['-date_demande'],
            },
        ),
    ]
