# Generated by Django 6.0.5 on 2026-07-21 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0020_demandetransfert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Ndjamena - Abeche (axe Est)', max_length=120)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='transport.compagnie')),
            ],
            options={
                'verbose_name': 'Ligne',
                'verbose_name_plural': 'Lignes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ArretLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField(help_text='1 = ville de depart, puis 2, 3, 4...')),
                ('prix_depuis_depart', models.IntegerField(default=0, help_text='Prix en FCFA depuis la ville de depart')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrets', to='transport.agence')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='transport.ligne')),
            ],
            options={
                'verbose_name': 'Arret de ligne',
                'verbose_name_plural': 'Arrets de ligne',
                'ordering': ['ligne', 'ordre'],
                'unique_together': {('ligne', 'ordre')},
            },
        ),
    ]
