# Generated by Django 6.0.5 on 2026-07-21 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_ligne_arretligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='ligne',
            field=models.ForeignKey(blank=True, help_text='Ligne desservie (si le voyage dessert plusieurs villes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.ligne'),
        ),
    ]
