# Generated by Django 6.0.5 on 2026-07-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_voyage_ligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='agence_destination',
            field=models.ForeignKey(blank=True, help_text='Ou le voyageur descend (si ligne multi-arrets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_destination', to='transport.agence'),
        ),
    ]
