# Generated by Django 6.0.5 on 2026-07-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_reservation_agence_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='agence_destination',
        ),
        migrations.RemoveField(
            model_name='siege',
            name='occupe',
        ),
        migrations.RemoveField(
            model_name='siege',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='arret_descente',
            field=models.ForeignKey(blank=True, help_text='Arret ou le voyageur descend (si ligne multi-arrets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_descente', to='transport.arretligne'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='arret_montee',
            field=models.ForeignKey(blank=True, help_text='Arret ou le voyageur monte (si ligne multi-arrets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_montee', to='transport.arretligne'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='siege',
            field=models.ForeignKey(blank=True, help_text='Siege physique reserve', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.siege'),
        ),
    ]
