# Generated by Django 6.0.5 on 2026-07-30 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_remove_reservation_agence_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_modifies', to='transport.employe', verbose_name='Modifie par'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_modifiees', to='transport.employe', verbose_name='Modifie par'),
        ),
        migrations.AddField(
            model_name='transfertargent',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_modifies', to='transport.employe', verbose_name='Modifie par'),
        ),
    ]
