# Generated by Django 6.0.5 on 2026-07-31 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0025_colis_modifie_par_reservation_modifie_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Agence de rattachement du chauffeur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs', to='transport.agence'),
        ),
    ]
