# Generated by Django 6.0.5 on 2026-07-31 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0026_chauffeur_agence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Agence de rattachement du bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='transport.agence'),
        ),
    ]
