# Generated by Django 6.0.5 on 2026-07-31 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_alter_employe_poste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion de ce chauffeur (cree par le PDG)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PositionBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vitesse_kmh', models.FloatField(blank=True, help_text='Vitesse en km/h si disponible', null=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='transport.chauffeur')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='transport.voyage')),
            ],
            options={
                'verbose_name': 'Position bus',
                'verbose_name_plural': 'Positions bus',
                'ordering': ['-horodatage'],
            },
        ),
    ]
