# Generated by Django 6.0.5 on 2026-08-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0029_chauffeur_user_positionbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('pdg', 'PDG / Directeur general'), ('responsable', "Responsable d'agence"), ('secretaire', "Secretaire d'agence"), ('resp_planning', 'Responsable planning'), ('guichetier', 'Guichetier / billettiste'), ('caissier', 'Caissier'), ('agent_colis', 'Agent colis'), ('agent_transfert', "Agent transfert d'argent"), ('manutentionnaire', 'Manutentionnaire / bagagiste'), ('comptable', 'Comptable'), ('rh', 'Responsable RH / recrutement'), ('resp_maintenance', 'Responsable maintenance'), ('securite', 'Agent de securite'), ('autre', 'Autre')], default='guichetier', max_length=20),
        ),
    ]
