# Generated by Django 6.0.5 on 2026-08-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0030_alter_employe_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='zone',
            field=models.CharField(blank=True, choices=[('nord', 'Nord'), ('sud', 'Sud')], help_text='Zone geographique (pour le planning)', max_length=10),
        ),
    ]
