# Generated by Django 6.0.5 on 2026-08-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0031_agence_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='zone',
            field=models.CharField(blank=True, choices=[('nord', 'Nord'), ('sud', 'Sud')], help_text='Zone geographique geree (uniquement pour Responsable planning)', max_length=10),
        ),
    ]
