# Generated by Django 6.0.5 on 2026-08-04 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0032_employe_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_embarquement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='embarque',
            field=models.BooleanField(default=False, help_text='Coche automatiquement quand le billet est scanne au controle'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='scanne_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_scannees', to='transport.employe', verbose_name='Scanne par'),
        ),
    ]
