# Generated by Django 6.0.5 on 2026-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0033_reservation_date_embarquement_reservation_embarque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('arret_anormal', 'Arret anormal')], default='arret_anormal', max_length=20)),
                ('message', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resolue', models.BooleanField(default=False, help_text='Cocher une fois verifiee par un responsable')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='transport.voyage')),
            ],
            options={
                'verbose_name': 'Alerte voyage',
                'verbose_name_plural': 'Alertes voyage',
                'ordering': ['-date_creation'],
            },
        ),
    ]
