# Generated by Django 6.0.5 on 2026-08-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0034_alertevoyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='niveau_fidelite',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('argent', 'Argent'), ('or', 'Or')], default='bronze', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='points_fidelite',
            field=models.IntegerField(default=0, help_text='1 point par 100 FCFA depense'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='points_attribues',
            field=models.BooleanField(default=False, help_text='Vrai si les points de fidelite ont deja ete comptes pour cette reservation'),
        ),
    ]
