# Generated by Django 6.0.5 on 2026-08-07 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0035_client_niveau_fidelite_client_points_fidelite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bonus_parrainage_attribue',
            field=models.BooleanField(default=False, help_text='Vrai si le bonus de parrainage a deja ete donne (au premier billet paye)'),
        ),
        migrations.AddField(
            model_name='client',
            name='code_parrainage',
            field=models.CharField(blank=True, help_text='Code unique que ce client partage a ses amis', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='parraine_par',
            field=models.ForeignKey(blank=True, help_text='Client qui a parraine ce client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='transport.client'),
        ),
    ]
