# Generated by Django 6.0.5 on 2026-08-07 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0036_client_bonus_parrainage_attribue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(help_text='Note globale de 1 a 5 etoiles')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire facultatif du client')),
                ('bus_propre', models.BooleanField(blank=True, help_text='Le bus etait-il propre ?', null=True)),
                ('climatisation_ok', models.BooleanField(blank=True, help_text='La climatisation fonctionnait-elle ?', null=True)),
                ('television_ok', models.BooleanField(blank=True, help_text='La television fonctionnait-elle ?', null=True)),
                ('connexion_ok', models.BooleanField(blank=True, help_text='La connexion Starlink fonctionnait-elle ?', null=True)),
                ('chauffeur_poli', models.BooleanField(blank=True, help_text='Le chauffeur etait-il poli ?', null=True)),
                ('accompagnateur_aimable', models.BooleanField(blank=True, help_text="L'accompagnateur etait-il aimable ?", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.chauffeur')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.client')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.reservation')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.voyage')),
            ],
            options={
                'verbose_name': 'Avis voyage',
                'verbose_name_plural': 'Avis voyages',
                'ordering': ['-date_creation'],
            },
        ),
    ]
