# Generated by Django 6.0.5 on 2026-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0037_avisvoyage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='La question posee', max_length=200)),
                ('reponse', models.TextField(help_text='La reponse affichee au client')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage (petit numero = en haut)")),
                ('actif', models.BooleanField(default=True, help_text='Decochez pour masquer sans supprimer')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Question FAQ',
                'verbose_name_plural': 'Questions FAQ',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
