# Generated by Django 6.0.5 on 2026-08-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0038_questionfaq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agence',
            options={'verbose_name': 'Agence', 'verbose_name_plural': 'Agences'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Bus'},
        ),
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Chauffeur', 'verbose_name_plural': 'Chauffeurs'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='colis',
            options={'ordering': ['-date_enregistrement'], 'verbose_name': 'Colis', 'verbose_name_plural': 'Colis'},
        ),
        migrations.AlterModelOptions(
            name='compagnie',
            options={'verbose_name': 'Compagnie', 'verbose_name_plural': 'Compagnies'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Employe', 'verbose_name_plural': 'Employes'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_reservation'], 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='siege',
            options={'ordering': ['voyage', 'numero'], 'verbose_name': 'Siege', 'verbose_name_plural': 'Sieges'},
        ),
        migrations.AlterModelOptions(
            name='trajet',
            options={'ordering': ['ville_depart', 'ville_arrivee'], 'verbose_name': 'Trajet', 'verbose_name_plural': 'Trajets'},
        ),
        migrations.AlterModelOptions(
            name='transfertargent',
            options={'ordering': ['-date_envoi'], 'verbose_name': "Transfert d'argent", 'verbose_name_plural': "Transferts d'argent"},
        ),
        migrations.AlterModelOptions(
            name='voyage',
            options={'ordering': ['-date_depart', '-heure_depart'], 'verbose_name': 'Voyage', 'verbose_name_plural': 'Voyages'},
        ),
        migrations.AlterField(
            model_name='agence',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='adresse',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agences', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='ville',
            field=models.CharField(max_length=50, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='agence',
            name='zone',
            field=models.CharField(blank=True, choices=[('nord', 'Nord'), ('sud', 'Sud')], help_text='Zone geographique (pour le planning)', max_length=10, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='alertevoyage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='alertevoyage',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='alertevoyage',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='alertevoyage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='alertevoyage',
            name='resolue',
            field=models.BooleanField(default=False, help_text='Cocher une fois verifiee par un responsable', verbose_name='Resolue'),
        ),
        migrations.AlterField(
            model_name='alertevoyage',
            name='type_alerte',
            field=models.CharField(choices=[('arret_anormal', 'Arret anormal')], default='arret_anormal', max_length=20, verbose_name="Type d'alerte"),
        ),
        migrations.AlterField(
            model_name='alertevoyage',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='transport.voyage', verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='arretligne',
            name='agence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrets', to='transport.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='arretligne',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='transport.ligne', verbose_name='Ligne'),
        ),
        migrations.AlterField(
            model_name='arretligne',
            name='ordre',
            field=models.IntegerField(help_text='1 = ville de depart, puis 2, 3, 4...', verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='arretligne',
            name='prix_depuis_depart',
            field=models.IntegerField(default=0, help_text='Prix en FCFA depuis la ville de depart', verbose_name='Prix depuis le depart'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='accompagnateur_aimable',
            field=models.BooleanField(blank=True, help_text="L'accompagnateur etait-il aimable ?", null=True, verbose_name='Accompagnateur aimable'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='bus_propre',
            field=models.BooleanField(blank=True, help_text='Le bus etait-il propre ?', null=True, verbose_name='Bus propre'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.chauffeur', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='chauffeur_poli',
            field=models.BooleanField(blank=True, help_text='Le chauffeur etait-il poli ?', null=True, verbose_name='Chauffeur poli'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='climatisation_ok',
            field=models.BooleanField(blank=True, help_text='La climatisation fonctionnait-elle ?', null=True, verbose_name='Climatisation OK'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Commentaire facultatif du client', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='connexion_ok',
            field=models.BooleanField(blank=True, help_text='La connexion Starlink fonctionnait-elle ?', null=True, verbose_name='Connexion OK'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='note',
            field=models.IntegerField(help_text='Note globale de 1 a 5 etoiles', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.reservation', verbose_name='Reservation'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='television_ok',
            field=models.BooleanField(blank=True, help_text='La television fonctionnait-elle ?', null=True, verbose_name='Television OK'),
        ),
        migrations.AlterField(
            model_name='avisvoyage',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='transport.voyage', verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Agence de rattachement du bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='transport.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='annee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Annee'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacite',
            field=models.IntegerField(verbose_name='Capacite'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date_assurance',
            field=models.DateField(blank=True, null=True, verbose_name='Date assurance'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='date_visite_technique',
            field=models.DateField(blank=True, null=True, verbose_name='Date visite technique'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='immatriculation',
            field=models.CharField(max_length=20, unique=True, verbose_name='Immatriculation'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='kilometrage',
            field=models.IntegerField(default=0, verbose_name='Kilometrage'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='marque',
            field=models.CharField(max_length=50, verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='modele',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modele'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='statut',
            field=models.CharField(choices=[('en_service', 'En service'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='en_service', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Agence de rattachement du chauffeur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs', to='transport.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='annees_experience',
            field=models.IntegerField(default=0, verbose_name="Annees d'experience"),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeurs', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_expiration_permis',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration du permis"),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='numero_permis',
            field=models.CharField(max_length=50, unique=True, verbose_name='Numero de permis'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='chauffeurs/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='statut',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_mission', 'En mission'), ('repos', 'En repos'), ('inactif', 'Inactif')], default='disponible', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion de ce chauffeur (cree par le PDG)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeur', to=settings.AUTH_USER_MODEL, verbose_name='Compte de connexion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bonus_parrainage_attribue',
            field=models.BooleanField(default=False, help_text='Vrai si le bonus de parrainage a deja ete donne (au premier billet paye)', verbose_name='Bonus parrainage attribue'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cni',
            field=models.CharField(blank=True, help_text="Numero de la piece d'identite", max_length=50, verbose_name='Numero de piece'),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_parrainage',
            field=models.CharField(blank=True, help_text='Code unique que ce client partage a ses amis', max_length=12, null=True, unique=True, verbose_name='Code de parrainage'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='niveau_fidelite',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('argent', 'Argent'), ('or', 'Or')], default='bronze', max_length=10, verbose_name='Niveau de fidelite'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_voyages',
            field=models.IntegerField(default=0, help_text='Nombre total de voyages effectues', verbose_name='Nombre de voyages'),
        ),
        migrations.AlterField(
            model_name='client',
            name='parraine_par',
            field=models.ForeignKey(blank=True, help_text='Client qui a parraine ce client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='transport.client', verbose_name='Parraine par'),
        ),
        migrations.AlterField(
            model_name='client',
            name='points_fidelite',
            field=models.IntegerField(default=0, help_text='1 point par 100 FCFA depense', verbose_name='Points de fidelite'),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20, verbose_name='Type de client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_piece',
            field=models.CharField(blank=True, choices=[('cni', "Carte nationale d'identite"), ('passeport', 'Passeport'), ('acte_naissance', 'Acte de naissance'), ('carte_pro', 'Carte professionnelle'), ('permis', 'Permis de conduire'), ('autre', 'Autre piece')], help_text="Type de piece d'identite", max_length=20, verbose_name='Type de piece'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion lie a cette fiche client (app mobile)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='Compte de connexion'),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville_residence',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ville de residence'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='agence_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_recus', to='transport.agence', verbose_name="Agence d'arrivee"),
        ),
        migrations.AlterField(
            model_name='colis',
            name='agence_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_envoyes', to='transport.agence', verbose_name='Agence de depart'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='code_suivi',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code de suivi'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='date_enregistrement',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='colis',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='description',
            field=models.CharField(help_text='Contenu du colis', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='destinataire_nom',
            field=models.CharField(max_length=100, verbose_name='Nom du destinataire'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='destinataire_telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone du destinataire'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='expediteur_nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='colis',
            name='expediteur_telephone',
            field=models.CharField(max_length=20, verbose_name="Telephone de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='colis',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='poids_kg',
            field=models.FloatField(help_text='Poids en kilogrammes', verbose_name='Poids (kg)'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='prix',
            field=models.IntegerField(help_text='Prix en FCFA', verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='statut',
            field=models.CharField(choices=[('enregistre', 'Enregistre'), ('en_transit', 'En transit'), ('arrive', 'Arrive a destination'), ('livre', 'Livre'), ('retourne', 'Retourne')], default='enregistre', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='voyage',
            field=models.ForeignKey(blank=True, help_text='Voyage sur lequel le colis est transporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis', to='transport.voyage', verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='siege_social',
            field=models.CharField(max_length=200, verbose_name='Siege social'),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='sigle',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='compagnie',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='agence_arrivee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_colis_arrivee', to='transport.agence', verbose_name="Agence d'arrivee"),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='agence_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_colis_depart', to='transport.agence', verbose_name='Agence de depart'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_colis', to='transport.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='colis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='transport.colis', verbose_name='Colis'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='destinataire_nom',
            field=models.CharField(max_length=100, verbose_name='Nom du destinataire'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='destinataire_telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone du destinataire'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='expediteur_nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='expediteur_telephone',
            field=models.CharField(max_length=20, verbose_name="Telephone de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='numero_demande',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numero de demande'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='poids_estime',
            field=models.FloatField(help_text='Poids estime en kg', verbose_name='Poids estime'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='poids_reel',
            field=models.FloatField(blank=True, help_text="Poids reel pese a l'agence (kg)", null=True, verbose_name='Poids reel'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='prix',
            field=models.IntegerField(blank=True, help_text="Prix fixe par l'agence (FCFA)", null=True, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validee (colis cree)'), ('annulee', 'Annulee')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='demandecolis',
            name='valeur_declaree',
            field=models.IntegerField(default=0, help_text='Valeur declaree en FCFA', verbose_name='Valeur declaree'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='agence_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_depart', to='transport.agence', verbose_name='Agence de depart'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='agence_retrait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_retrait', to='transport.agence', verbose_name='Agence de retrait'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='beneficiaire_nom',
            field=models.CharField(max_length=100, verbose_name='Nom du beneficiaire'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='beneficiaire_telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone du beneficiaire'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert', to='transport.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='expediteur_nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='expediteur_telephone',
            field=models.CharField(max_length=20, verbose_name="Telephone de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='frais',
            field=models.IntegerField(blank=True, help_text="Frais fixes par l'agence", null=True, verbose_name='Frais'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='montant',
            field=models.IntegerField(help_text='Montant a envoyer en FCFA', verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='numero_demande',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numero de demande'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validee (transfert cree)'), ('annulee', 'Annulee')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='demandetransfert',
            name='transfert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='transport.transfertargent', verbose_name='Transfert'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un PDG (toute la compagnie)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='transport.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='cni',
            field=models.CharField(blank=True, help_text="Numero de carte d'identite", max_length=50, verbose_name='Numero de piece'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('pdg', 'PDG / Directeur general'), ('responsable', "Responsable d'agence"), ('secretaire', "Secretaire d'agence"), ('resp_planning', 'Responsable planning'), ('guichetier', 'Guichetier / billettiste'), ('caissier', 'Caissier'), ('agent_colis', 'Agent colis'), ('agent_transfert', "Agent transfert d'argent"), ('manutentionnaire', 'Manutentionnaire / bagagiste'), ('comptable', 'Comptable'), ('rh', 'Responsable RH / recrutement'), ('resp_maintenance', 'Responsable maintenance'), ('securite', 'Agent de securite'), ('autre', 'Autre')], default='guichetier', max_length=20, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prenom'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='salaire',
            field=models.IntegerField(blank=True, help_text='Salaire mensuel en FCFA', null=True, verbose_name='Salaire'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Compte de connexion lie a cet employe', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employe', to=settings.AUTH_USER_MODEL, verbose_name='Compte de connexion'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='zone',
            field=models.CharField(blank=True, choices=[('nord', 'Nord'), ('sud', 'Sud')], help_text='Zone geographique geree (uniquement pour Responsable planning)', max_length=10, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='entretien',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='nom',
            field=models.CharField(help_text='Ex : Ndjamena - Abeche (axe Est)', max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='pleincarburant',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='positionbus',
            name='chauffeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='transport.chauffeur', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='positionbus',
            name='horodatage',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horodatage'),
        ),
        migrations.AlterField(
            model_name='positionbus',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='positionbus',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='positionbus',
            name='vitesse_kmh',
            field=models.FloatField(blank=True, help_text='Vitesse en km/h si disponible', null=True, verbose_name='Vitesse (km/h)'),
        ),
        migrations.AlterField(
            model_name='positionbus',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='transport.voyage', verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='actif',
            field=models.BooleanField(default=True, help_text='Decochez pour masquer', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date_debut',
            field=models.DateField(help_text='Date de debut de validite', verbose_name='Date de debut'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='date_fin',
            field=models.DateField(help_text='Date de fin de validite', verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Image de la promotion', null=True, upload_to='promotions/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='service',
            field=models.CharField(choices=[('voyage', 'Reservation de voyage'), ('colis', 'Envoi de colis'), ('transfert', "Transfert d'argent"), ('aucun', 'Aucun')], default='aucun', help_text='Vers quel service renvoie la promotion', max_length=20, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='texte',
            field=models.TextField(help_text='Description de la promotion', verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='titre',
            field=models.CharField(help_text='Titre de la promotion', max_length=120, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='questionfaq',
            name='actif',
            field=models.BooleanField(default=True, help_text='Decochez pour masquer sans supprimer', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='questionfaq',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='questionfaq',
            name='ordre',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage (petit numero = en haut)", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='questionfaq',
            name='question',
            field=models.CharField(help_text='La question posee', max_length=200, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='questionfaq',
            name='reponse',
            field=models.TextField(help_text='La reponse affichee au client', verbose_name='Reponse'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Agence ou la reservation a ete faite', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arret_descente',
            field=models.ForeignKey(blank=True, help_text='Arret ou le voyageur descend (si ligne multi-arrets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_descente', to='transport.arretligne', verbose_name='Arret de descente'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arret_montee',
            field=models.ForeignKey(blank=True, help_text='Arret ou le voyageur monte (si ligne multi-arrets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_montee', to='transport.arretligne', verbose_name='Arret de montee'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_embarquement',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'embarquement"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='embarque',
            field=models.BooleanField(default=False, help_text='Coche automatiquement quand le billet est scanne au controle', verbose_name='Embarque'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('especes', 'Especes'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement bancaire'), ('carte', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='montant_total',
            field=models.IntegerField(blank=True, default=0, help_text='Calcule automatiquement', verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_places',
            field=models.IntegerField(default=1, verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numero de reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='points_attribues',
            field=models.BooleanField(default=False, help_text='Vrai si les points de fidelite ont deja ete comptes pour cette reservation', verbose_name='Points attribues'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='siege',
            field=models.ForeignKey(blank=True, help_text='Siege physique reserve', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.siege', verbose_name='Siege'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('payee', 'Payee'), ('annulee', 'Annulee'), ('remboursee', 'Remboursee')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='transport.voyage', verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyageur_nom',
            field=models.CharField(blank=True, help_text='Nom du voyageur de ce billet', max_length=100, verbose_name='Nom du voyageur'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyageur_numero_piece',
            field=models.CharField(blank=True, help_text='Numero de piece du voyageur', max_length=50, verbose_name='Numero de piece du voyageur'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyageur_prenom',
            field=models.CharField(blank=True, help_text='Prenom du voyageur', max_length=100, verbose_name='Prenom du voyageur'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyageur_telephone',
            field=models.CharField(blank=True, help_text='Telephone du voyageur', max_length=20, verbose_name='Telephone du voyageur'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='voyageur_type_piece',
            field=models.CharField(blank=True, help_text='Type de piece du voyageur', max_length=20, verbose_name='Type de piece du voyageur'),
        ),
        migrations.AlterField(
            model_name='siege',
            name='numero',
            field=models.IntegerField(help_text='Numero du siege', verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='siege',
            name='voyage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieges', to='transport.voyage', verbose_name='Voyage'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='distance_km',
            field=models.IntegerField(help_text='Distance en kilometres', verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='duree_estimee_heures',
            field=models.FloatField(help_text='Duree estimee en heures', verbose_name='Duree estimee (heures)'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='prix_base',
            field=models.IntegerField(help_text='Prix du billet en FCFA', verbose_name='Prix de base'),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='ville_arrivee',
            field=models.CharField(max_length=50, verbose_name="Ville d'arrivee"),
        ),
        migrations.AlterField(
            model_name='trajet',
            name='ville_depart',
            field=models.CharField(max_length=50, verbose_name='Ville de depart'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='agence_depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_envoyes', to='transport.agence', verbose_name='Agence de depart'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='agence_retrait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_recus', to='transport.agence', verbose_name='Agence de retrait'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='beneficiaire_nom',
            field=models.CharField(max_length=100, verbose_name='Nom du beneficiaire'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='beneficiaire_telephone',
            field=models.CharField(max_length=20, verbose_name='Telephone du beneficiaire'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='code_retrait',
            field=models.CharField(blank=True, help_text='Code secret remis au beneficiaire', max_length=10, verbose_name='Code de retrait'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='code_transfert',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code de transfert'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='compagnie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='transport.compagnie', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='date_retrait',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de retrait'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='expediteur_nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='expediteur_telephone',
            field=models.CharField(max_length=20, verbose_name="Telephone de l'expediteur"),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='frais',
            field=models.IntegerField(default=0, help_text='Frais de transfert en FCFA', verbose_name='Frais'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='montant',
            field=models.IntegerField(help_text='Montant envoye en FCFA', verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de retrait'), ('retire', 'Retire'), ('annule', 'Annule'), ('rembourse', 'Rembourse')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.bus', verbose_name='Bus'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='chauffeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.chauffeur', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de creation'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='date_depart',
            field=models.DateField(verbose_name='Date de depart'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='heure_arrivee_prevue',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivee prevue"),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='heure_depart',
            field=models.TimeField(verbose_name='Heure de depart'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='ligne',
            field=models.ForeignKey(blank=True, help_text='Ligne desservie (si le voyage dessert plusieurs villes)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.ligne', verbose_name='Ligne'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='places_disponibles',
            field=models.IntegerField(verbose_name='Places disponibles'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='prix',
            field=models.IntegerField(help_text='Prix du billet en FCFA', verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='statut',
            field=models.CharField(choices=[('programme', 'Programme'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('annule', 'Annule')], default='programme', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voyages', to='transport.trajet', verbose_name='Trajet'),
        ),
    ]
