# Generated by Django 6.0.5 on 2026-08-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0039_alter_agence_options_alter_bus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='voyageur_date_emission',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'emission de la piece"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyageur_date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration de la piece"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='voyageur_nationalite',
            field=models.CharField(blank=True, help_text='Nationalite indiquee sur la piece', max_length=50, verbose_name='Nationalite du voyageur'),
        ),
    ]
