# Generated by Django 6.0.5 on 2026-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0040_reservation_voyageur_date_emission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecolis',
            name='destinataire_nationalite',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nationalite du destinataire'),
        ),
        migrations.AddField(
            model_name='demandecolis',
            name='destinataire_numero_piece',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero de piece du destinataire'),
        ),
        migrations.AddField(
            model_name='demandecolis',
            name='destinataire_type_piece',
            field=models.CharField(blank=True, max_length=20, verbose_name='Type de piece du destinataire'),
        ),
        migrations.AddField(
            model_name='demandecolis',
            name='expediteur_nationalite',
            field=models.CharField(blank=True, max_length=50, verbose_name="Nationalite de l'expediteur"),
        ),
        migrations.AddField(
            model_name='demandecolis',
            name='expediteur_numero_piece',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numero de piece de l'expediteur"),
        ),
        migrations.AddField(
            model_name='demandecolis',
            name='expediteur_type_piece',
            field=models.CharField(blank=True, max_length=20, verbose_name="Type de piece de l'expediteur"),
        ),
        migrations.AddField(
            model_name='demandetransfert',
            name='beneficiaire_nationalite',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nationalite du beneficiaire'),
        ),
        migrations.AddField(
            model_name='demandetransfert',
            name='beneficiaire_numero_piece',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero de piece du beneficiaire'),
        ),
        migrations.AddField(
            model_name='demandetransfert',
            name='beneficiaire_type_piece',
            field=models.CharField(blank=True, max_length=20, verbose_name='Type de piece du beneficiaire'),
        ),
        migrations.AddField(
            model_name='demandetransfert',
            name='expediteur_nationalite',
            field=models.CharField(blank=True, max_length=50, verbose_name="Nationalite de l'expediteur"),
        ),
        migrations.AddField(
            model_name='demandetransfert',
            name='expediteur_numero_piece',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numero de piece de l'expediteur"),
        ),
        migrations.AddField(
            model_name='demandetransfert',
            name='expediteur_type_piece',
            field=models.CharField(blank=True, max_length=20, verbose_name="Type de piece de l'expediteur"),
        ),
    ]
