# Generated by Django 6.0.5 on 2026-08-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0042_colis_destinataire_nationalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colis',
            name='code_retrait',
            field=models.CharField(blank=True, help_text='Code secret remis au destinataire, exige a la remise', max_length=10, verbose_name='Code de retrait'),
        ),
    ]
