# Generated by Django 6.0.5 on 2026-08-23 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0047_alertes_expiration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConfirmationAppareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_appareil', models.CharField(max_length=100, verbose_name="Identifiant de l'appareil")),
                ('jeton', models.CharField(max_length=64, unique=True, verbose_name='Jeton')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('utilisee', models.BooleanField(default=False, verbose_name='Utilisee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_appareil', to=settings.AUTH_USER_MODEL, verbose_name='Compte')),
            ],
            options={
                'verbose_name': "Demande de confirmation d'appareil",
                'verbose_name_plural': "Demandes de confirmation d'appareil",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AppareilConfirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant_appareil', models.CharField(max_length=100, verbose_name="Identifiant de l'appareil")),
                ('date_confirmation', models.DateTimeField(auto_now_add=True, verbose_name='Date de confirmation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils_confirmes', to=settings.AUTH_USER_MODEL, verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Appareil confirme',
                'verbose_name_plural': 'Appareils confirmes',
                'unique_together': {('user', 'identifiant_appareil')},
            },
        ),
    ]
