# Generated by Django 6.0.5 on 2026-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0048_demandeconfirmationappareil_appareilconfirme'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profils_clients/', verbose_name='Photo de profil'),
        ),
    ]
