# Generated by Django 6.0.5 on 2026-08-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0049_client_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employes/', verbose_name='Photo'),
        ),
    ]
