# Generated by Django 6.0.5 on 2026-08-23 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0050_employe_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plainte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=150, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours de traitement'), ('traitee', 'Traitee')], default='nouvelle', max_length=20, verbose_name='Statut')),
                ('reponse', models.TextField(blank=True, help_text="Reponse donnee au client, visible dans l'app", verbose_name='Reponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de reponse')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes', to='transport.client', verbose_name='Client')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintes_traitees', to='transport.employe', verbose_name='Traite par')),
            ],
            options={
                'verbose_name': 'Plainte',
                'verbose_name_plural': 'Plaintes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
