# Generated by Django 6.0.5 on 2026-09-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0051_plainte'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='zone',
            field=models.CharField(blank=True, choices=[('nord', 'Nord'), ('sud', 'Sud')], help_text='Zone geographique (pour le filtrage par responsable planning)', max_length=10, verbose_name='Zone'),
        ),
    ]
