# Generated by Django 6.0.5 on 2026-09-26 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0052_trajet_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name="Nom de l'article")),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='Reference')),
                ('unite', models.CharField(default='piece', help_text='Ex : piece, litre, kg...', max_length=20, verbose_name='Unite')),
                ('quantite_stock', models.PositiveIntegerField(default=0, verbose_name='Quantite en stock')),
                ('seuil_alerte', models.PositiveIntegerField(default=5, help_text="En dessous de ce niveau, l'article est signale comme stock faible", verbose_name="Seuil d'alerte")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Article de stock',
                'verbose_name_plural': 'Articles de stock',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='employe',
            name='agence',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour un PDG ou un Magasinier (magasin unique pour toute la compagnie)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='transport.agence', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.CharField(choices=[('pdg', 'PDG / Directeur general'), ('responsable', "Responsable d'agence"), ('secretaire', "Secretaire d'agence"), ('resp_planning', 'Responsable planning'), ('guichetier', 'Guichetier / billettiste'), ('caissier', 'Caissier'), ('agent_colis', 'Agent colis'), ('agent_transfert', "Agent transfert d'argent"), ('manutentionnaire', 'Manutentionnaire / bagagiste'), ('comptable', 'Comptable'), ('rh', 'Responsable RH / recrutement'), ('resp_maintenance', 'Responsable maintenance'), ('magasinier', 'Magasinier'), ('securite', 'Agent de securite'), ('autre', 'Autre')], default='guichetier', max_length=20, verbose_name='Poste'),
        ),
        migrations.CreateModel(
            name='DemandeMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantite demandee')),
                ('description', models.TextField(blank=True, help_text='Details complementaires (facultatif)', verbose_name='Precisions')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmee (materiel disponible)'), ('refusee', 'Refusee'), ('livree', 'Livree')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('reponse_magasin', models.TextField(blank=True, help_text='Ex : delai de livraison, ou raison du refus (rupture de stock...)', verbose_name='Reponse du magasin')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='transport.articlestock', verbose_name='Article')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_materiel', to='transport.bus', verbose_name='Bus')),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_materiel_creees', to='transport.employe', verbose_name='Demande par')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_materiel_traitees', to='transport.employe', verbose_name='Traite par (magasin)')),
            ],
            options={
                'verbose_name': 'Demande de materiel',
                'verbose_name_plural': 'Demandes de materiel',
                'ordering': ['-date_demande'],
            },
        ),
    ]
