# Generated by Django 6.0.5 on 2026-09-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0053_articlestock_alter_employe_agence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandemateriel',
            name='vu_par_demandeur',
            field=models.BooleanField(default=True, help_text="Mis a False des que le magasin traite la demande, pour notifier le responsable qui l'a creee", verbose_name='Vu par le demandeur'),
        ),
    ]
