# Generated by Django 6.0.5 on 2026-10-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0054_demandemateriel_vu_par_demandeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestock',
            name='prix_unitaire',
            field=models.PositiveIntegerField(default=0, help_text="Prix d'un seul exemplaire de cet article", verbose_name='Prix unitaire (FCFA)'),
        ),
    ]
