# Generated by Django 6.0.5 on 2026-10-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0055_articlestock_prix_unitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnie',
            name='telephones_recus',
            field=models.CharField(blank=True, help_text="Un ou plusieurs numeros separes par ' / ', ex : 60 10 06 88 / 66 66 27 27", max_length=200, verbose_name='Telephones affiches sur les billets/recus'),
        ),
    ]
