# Generated by Django 6.0.5 on 2026-10-02 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0056_compagnie_telephones_recus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commissionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Telephone')),
                ('commission_par_billet', models.PositiveIntegerField(default=0, help_text='Montant verse au commissionnaire pour chaque billet apporte', verbose_name='Commission par billet (FCFA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissionnaires', to='transport.agence', verbose_name='Agence')),
            ],
            options={
                'verbose_name': 'Commissionnaire',
                'verbose_name_plural': 'Commissionnaires',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='commissionnaire',
            field=models.ForeignKey(blank=True, help_text='Intermediaire qui a apporte ce client (facultatif)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='transport.commissionnaire', verbose_name='Commissionnaire'),
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='Motif de la depense')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_creees', to='transport.employe', verbose_name='Enregistre par')),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='transport.voyage', verbose_name='Voyage')),
            ],
            options={
                'verbose_name': 'Depense de voyage',
                'verbose_name_plural': 'Depenses de voyage',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('pause', 'En pause'), ('cloturee', 'Cloturee')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('ouverte_le', models.DateTimeField(auto_now_add=True, verbose_name='Ouverte le')),
                ('cloturee_le', models.DateTimeField(blank=True, null=True, verbose_name='Cloturee le')),
                ('fond_initial', models.PositiveIntegerField(default=0, verbose_name="Fond de caisse a l'ouverture (FCFA)")),
                ('pause_depuis', models.DateTimeField(blank=True, null=True, verbose_name='En pause depuis')),
                ('secondes_pause', models.PositiveIntegerField(default=0, verbose_name='Duree totale des pauses (secondes)')),
                ('montant_compte', models.IntegerField(blank=True, null=True, verbose_name='Montant compte a la cloture (FCFA)')),
                ('ecart', models.IntegerField(blank=True, help_text='Montant compte moins montant attendu', null=True, verbose_name='Ecart (FCFA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='transport.agence', verbose_name='Agence')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_caisse', to='transport.employe', verbose_name='Caissier')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-ouverte_le'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('encaissement', 'Encaissement'), ('decaissement', 'Decaissement')], max_length=15, verbose_name='Type')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (FCFA)')),
                ('motif', models.CharField(max_length=150, verbose_name='Motif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse', to='transport.employe', verbose_name='Enregistre par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='transport.sessioncaisse', verbose_name='Session de caisse')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-date_creation'],
            },
        ),
    ]
