# Generated by Django 6.0.5 on 2026-10-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0057_caisse_depenses_commissionnaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='infos_passagers',
            field=models.CharField(blank=True, help_text='Autres informations imprimees sur le billet (ex : climatisation, prises USB)', max_length=200, verbose_name='Infos pour les passagers'),
        ),
        migrations.AddField(
            model_name='bus',
            name='wifi_code',
            field=models.CharField(blank=True, help_text='Mot de passe du Wi-Fi du bus (imprime sur le billet)', max_length=60, verbose_name='Code du Wi-Fi'),
        ),
        migrations.AddField(
            model_name='bus',
            name='wifi_nom',
            field=models.CharField(blank=True, help_text='Nom du reseau Wi-Fi du bus (imprime sur le billet)', max_length=60, verbose_name='Nom du Wi-Fi'),
        ),
    ]
